# syntax=docker/dockerfile:1
FROM node:22-alpine AS build

WORKDIR /usr/src/app/frontend
COPY package*.json ./
RUN npm ci
COPY . .

RUN npm run build

# ---- Production stage ----
FROM nginx:stable-alpine
COPY --from=build /usr/src/app/frontend/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]