services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./config.env
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
      - /usr/src/app/backend/generated

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules